version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: project_db
    env_file: ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080

  web:
    image: node:16
    working_dir: /src
    volumes:
      - "./app:/src/app"
    command: npm run start:dev
    depends_on: 
      - db
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT