version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: project_db
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080

  web:
    build: .
    volumes:
      - "./app:/src/app"
    command: npm run start:dev
    depends_on: 
      - db
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT